### ISSUE TITLE
Invite to be Owner

### ISSUE THREAD

**Issue by theo-armour** [launchandlearn/launchandlearn.github.io#3]
@AshwinThomas0 

Please accept new invite to be an owner not just a collaborator of this organization.

You may close this issue once you have accepted the invite

**Comment by theo-armour** [comment]
@AshwinThomas0 

You have accepted the first invitation to collaborate.

You have *not* accepted the second invitation to be an owner.

Please look for the invite and accept. There are many things you can do only if you are an owner.

**Comment by AshwinThomas0** [comment]
Can you please let me know if that worked. Found a link and accepted to be an owner

**Comment by AshwinThomas0** [comment]
https://www.dropbox.com/s/qk2zsmohqwsmgy8/Screenshot%202018-07-13%2019.06.13.png?dl=0

Is this right ?

**Comment by AshwinThomas0** [comment]
https://www.dropbox.com/s/udqe365q99qvc26/Screenshot%202018-07-13%2019.07.47.png?dl=0

Email showed me this and it gets to the same page so I guess it's done.

**Comment by theo-armour** [comment]
@AshwinThomas0 

You are now an owner of the _Launch and Learn_ GitHub organization. Yay!

Please go here and update your ownership to public:

https://github.com/orgs/launchandlearn/people

**Comment by AshwinThomas0** [comment]
done
